name: VolterTracker
version: 1.0
main: com.voltermc.voltertracker.VolterTracker
api-version: 1.20
commands:
  voltertracker:
    description: Set the webhook for Discord logging
    usage: /voltertracker setlog <webhook-url>
    permission: voltertracker.setlog
permissions:
  voltertracker.setlog:
    description: Allows setting the Discord webhook
    default: op
